version: "3.7"

services:
  nginx:
    image: "nginx:1.21.4"
    ports:
      - target: 80
        published: ${goodPort}
        protocol: tcp
        mode: ingress
    volumes:
      - ./htdocs:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

