version: "3.7"

services:
        nginx:
                image: "nginx"
                networks:
                        - traefik
                ports:
                        - target: 80
                          published: 58001
                          protocol: tcp
                          mode: ingress
                volumes:
                        - ./htdocs:/usr/share/nginx/html
                deploy:
                        labels: 
                          - "traefik.enable=true" 
                          - "traefik.docker.network=traefik_proxy_net"
                          - "traefik.http.routers.${SiteName}_router.rule=Host(`${SiteName}`)"
                          - "traefik.http.services.${SiteName_service.loadbalancer.server.port=80"
                          - "traefik.port=80"
                          - "traefik.site.port=80"
                          - "traefik.http.routers.${SiteName}_webserver.entrypoints=web"
                          - "traefik.http.routers.${SiteName}_webserver.middlewares=redirect"
                          - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
                          - "traefik.http.routers.${SiteName}_webserver2.tls=true"
                          - "traefik.http.routers.${SiteName}_webserver2.rule=Host(`${SiteName}`)"
                          - "traefik.http.routers.${SiteName}_webserver2.entrypoints=websecure"
                          - "traefik.http.routers.${SiteName}_webserver2.tls.certresolver=le"

networks:
        traefik:
                name: traefik_proxy_net
                external: true

